package db;
// Generated Mar 19, 2014 2:59:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer id;
	private String name;

	public Customer() {
	}

	public Customer(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
